name: Update README with Latest Repos

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch latest repos & build section
        run: |
          echo "Fetching repos..."

          REPOS=$(curl -s https://api.github.com/users/RasikhAli/repos?sort=updated&per_page=5)

          OUTPUT=""

          echo "$REPOS" | jq -c '.[]' | while read repo; do
            NAME=$(echo $repo | jq -r '.name')
            DESC=$(echo $repo | jq -r '.description // "No description provided"')
            URL=$(echo $repo | jq -r '.html_url')
            LANG=$(echo $repo | jq -r '.language // "N/A"')

            OUTPUT="${OUTPUT}\n### 📌 ${NAME}\n\n${DESC}\n\n**Tech Stack:** ${LANG}\n\n🔗 GitHub Repository: ${URL}\n\n---\n"
          done

          awk -v new="$OUTPUT" '
          BEGIN {p=1}
          /<!-- LATEST_REPOS_START -->/ {
            print;
            print new;
            p=0;
          }
          /<!-- LATEST_REPOS_END -->/ {
            p=1;
          }
          p
          ' README.md > temp.md && mv temp.md README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "🔄 Update latest repositories" || exit 0
          git push
